### ISSUE TITLE
Fastify v5 fails with HTTP 415 FST_ERR_CTP_INVALID_MEDIA_TYPE

### ISSUE THREAD

**Issue by nioc** [fox1t/fastify-multer#35]
When I upgrade from Fastify v4.28 to 5.2, uploads of multipart/form-data failed with a 415 HTTP:
``` json
{
  "code": "FST_ERR_CTP_INVALID_MEDIA_TYPE",
  "name": "FastifyError",
  "statusCode": 415,
  "message": "Unsupported Media Type: multipart/form-data; boundary=---------------------------33065737953259411260621758869"
}
```

I found a workaround by replacing the [standard](https://github.com/fox1t/fastify-multer/blob/master/src/lib/content-parser.ts#L14-L15) :

``` js
server.register(multer.contentParser)
```

with the following:

``` js
server.addContentTypeParser('multipart/form-data', function (request, payload, done) {
  done(null)
})
```

I suggest you change the code on [`lib/content-parser.ts`](https://github.com/fox1t/fastify-multer/blob/master/src/lib/content-parser.ts#L27) with:
``` js
  fastify.addContentTypeParser('multipart/form-data', setMultipart)
```

**Comment by samchon** [comment]
@fox1t Hope your upgrading

**Comment by dimbslmh** [comment]
Fastify v5.7.2 https://github.com/fastify/fastify/pull/6414 causing:

```
/usr/src/app/node_modules/fastify/lib/content-type-parser.js:81
        throw new FST_ERR_CTP_INVALID_TYPE()
        ^
FastifyError [Error]: The content type should be a string or a RegExp
    at ContentTypeParser.add (/usr/src/app/node_modules/fastify/lib/content-type-parser.js:81:15)
    at Object.addContentTypeParser (/usr/src/app/node_modules/fastify/lib/content-type-parser.js:360:30)
    at fastifyMulter (/usr/src/app/node_modules/fastify-multer/lib/lib/content-parser.js:19:13)
    at Plugin.exec (/usr/src/app/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/usr/src/app/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'FST_ERR_CTP_INVALID_TYPE',
  statusCode: 500
}
```
